# Generated by Django 4.1.1 on 2022-09-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
