# Generated by Django 4.1.1 on 2022-09-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_delete_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='this is title', max_length=50),
        ),
    ]
