# Generated by Django 4.1.1 on 2022-11-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_album_artist_song_album_artist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
