# Generated by Django 4.1.1 on 2022-11-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_alter_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='artist_name',
        ),
    ]
