# Generated by Django 4.1.1 on 2022-11-02 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_rename_name_artist_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='song_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
