# Generated by Django 4.1.1 on 2022-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_album_album_name_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
