# Generated by Django 4.1.1 on 2022-11-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_movie_slug_alter_movie_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='person_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.person'),
        ),
    ]
